spring:
  application:
    name: resource-reservation-engine
  datasource:
    url: jdbc:mysql://localhost:${DB_PORT:3306}/reservation_engine
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 86400000

admin:
  email: ${ADMIN_EMAIL:admin@reservation-engine.local}
  password: ${ADMIN_PASSWORD:pass123}